name: "Download artifact"
description: "Download an artifact"
inputs:
  workflow_file:
    description: 'Name of the worklow file'
  artifact:
    description: 'Name of the artifact'
  github_token:
    description: 'GH Token'

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ inputs.workflow_file }}
        name: ${{ inputs.artifact }}
        path: ${{ inputs.artifact }}
        commit: ${{ github.sha }}
        github_token: ${{ inputs.github_token }}
        if_no_artifact_found: ignore