name: B

on:
  workflow_run:
    workflows: [A1, A2]
    branches: [main]
    types: 
      - completed
    
jobs:   
  combine:
    name: Combine
# kind of irrelevant if we have to check if the file is there anyway
# if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/download_artifact
      with:
        workflow_file: A1.yml
        artifact: a1-j1
        github_token: ${{ secrets.GH_TOKEN }}

    - uses: ./.github/actions/download_artifact
      with:
        workflow_file: A1.yml
        artifact: a1-j2
        github_token: ${{ secrets.GH_TOKEN }}

    - uses: ./.github/actions/download_artifact
      with:
        workflow_file: A2.yml
        artifact: a2-j1
        github_token: ${{ secrets.GH_TOKEN }}

    - name: Display structure of downloaded files
      run: ls -R