name: B

on:
  workflow_run:
    workflows: [A1, A2]
    branches: [main]
    types: 
      - completed
    
jobs:   
  combine:
    name: Combine
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          
      - name: Display structure of downloaded files
        run: ls -R