name: B

on:
  trigger_a1:
    workflows: [A1]
    branches: [main]
    types: 
      - completed
  
  trigger_a2:
    workflows: [A2]
    branches: [main]
    types: 
      - completed
    
jobs:   
  combine:
    name: Combine
    if: ${{ github.event.trigger_a1.conclusion == 'success' && github.event.trigger_a2.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          
      - name: Display structure of downloaded files
        run: ls -R