name: B

on:
  workflow_run:
    workflows: [A1, A2]
    branches: [main]
    types: 
      - completed
    
jobs:   
  combine:
    name: Combine
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:

    - name: Download artifact A1J1
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: A1.yml
        name: a1-j1
        path: a1-j1
        github_token: ${{ secrets.GH_TOKEN }}
        if_no_artifact_found: ignore

    - name: Download artifact A1J2
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: A1.yml
        name: a1-j2
        path: a1-j2
        github_token: ${{ secrets.GH_TOKEN }}
        if_no_artifact_found: ignore


    - name: Download artifact A2J1
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: A2.yml 
        path: a2-j1
        github_token: ${{ secrets.GH_TOKEN }}
        if_no_artifact_found: ignore

    - name: Display structure of downloaded files
      run: ls -R