name: B

on:
  workflow_run:
    workflows: [A1, A2]
    branches: [main]
    types: 
      - completed
    
jobs:   
  combine:
    name: Combine
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:

    - name: Download artifact A1
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: a1.yml  

    - name: Download artifact A2
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: a2.yml  

    - name: Display structure of downloaded files
      run: ls -R